apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: ns-wordpress
spec:
  selector:
    app: wordpress-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-app
  namespace: ns-wordpress
spec:
  type: NodePort
  selector:
    app: wordpress-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
